### ISSUE TITLE
Landroid Card is completely empty in Dashboard

### ISSUE THREAD

**Issue by Dermaschinistas** [Barma-lej/landroid-card#175]
## **Describe the bug**

After installaton of Landroid Card via HACS and choosing the Card in HA Dashboard it just show a horizontal line.

A restart of Homeassistant was done. Browser cache was deleted as well. Same result with Chrome / Firefox or Mobile app. Also the Frontend Cache was erased.

In location Settings ->Dashboards->Ressources I have only one listed /hacsfiles/....etc

Deinstalling the Landroid card or reloading it is not changing anything.

No errors in HA Logs

See below some pictures during adding the Card to HA Dashboard and final appearance (snapshots from Mobile APP but same behaviour with Chrome Browser or Firefox)

![grafik](https://github.com/Barma-lej/landroid-card/assets/129041093/53745b3a-7951-40b0-8693-e67ec46d03e4)

![grafik](https://github.com/Barma-lej/landroid-card/assets/129041093/c8941e22-66de-4682-b54f-acc00d43099d)

![grafik](https://github.com/Barma-lej/landroid-card/assets/129041093/25318cc0-b4f2-461f-b63b-e783183ced8a)

The horizontal line underneath the washing mashine symbol (Waschmaschine) is all what I get. 

## **Versions:**

- Release: 0.2.9
- App: 2023.460 
- HomeAssistant version: 2023.7.2
- Landroid_cloud integration 3.0.5

**Comment by Barma-lej** [comment]
Which themes and custom cards do you have?

**Comment by crazychatting** [comment]
same here with latest HA. Installed via HACS, restarted and cleared browser cache:
```
gardena-mower-card.js:2  Uncaught ReferenceError: Polymer is not defined
    at gardena-mower-card.js:2:32
landroid-card.js?hacstag=510045489029:1  LANDROID-CARD  0.2.9 
landroid-card.js?hacstag=510045489029:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'time_extension')
    at uc.getAttributes (landroid-card.js?hacstag=510045489029:1:190965)
    at uc.render (landroid-card.js?hacstag=510045489029:1:208213)
    at uc.update (landroid-card.js?hacstag=510045489029:1:35869)
    at uc.performUpdate (landroid-card.js?hacstag=510045489029:1:27053)
    at uc.scheduleUpdate (landroid-card.js?hacstag=510045489029:1:26700)
    at uc._$Ej (landroid-card.js?hacstag=510045489029:1:26608)
```

**Comment by TheRealSimon42** [comment]
Same for me, but another function:

<img width="1282" alt="Google Chrome - DevTools - 192 168 0 2008123lovelacetest_2023-08-13_13 33 39@2x" src="https://github.com/Barma-lej/landroid-card/assets/62359912/dcd2e91d-78a8-4dd2-976d-69411e6f973d">

FYI: This error is logged when editing the card, ~~otherwise there is no error (see Console log above, Card is loaded) but the Card is empty.~~

-> My Bad, the mowers were not available. Reloading the Integration fixed the card from being empty. Maybe you should include an error image to indicate when the entity is just not available? (Just an Idea, don't know if this is possible)

**Comment by pixelsucht** [comment]
I'm having the same problem. Card is empty. JS Error / time_estimation.
I have no other custom cards and the default Home Assistant Template.
Home Assistant OS 10.5 / 2023.9.2

**Comment by Barma-lej** [comment]
Is there `time_extension` attribute in `schedule` section in mower?

**Comment by Barma-lej** [comment]
Please check the new version 0.3.0

**Comment by crazychatting** [comment]
still empty but now with another error:
```
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'id' in NONE
```
![image](https://github.com/Barma-lej/landroid-card/assets/36714171/73d19253-39e1-473f-b474-67a83d402061)

**Comment by Barma-lej** [comment]
Do you have a landroid_cloud integration? Do you have any attributes in your `vacuum.NAME_OF_YOUR_MOWER`?

**Comment by pixelsucht** [comment]
> Is there `time_extension` attribute in `schedule` section in mower?

Hi, i had the exact same Error as @TheRealSimon42. I now discovered also, that the error is caused if the mower is not available. (I didn't know its not available, had a Wifi error). As soon as the Mower is available there is no error and the card is filled.

**Comment by Barma-lej** [comment]
Hello, everyone. I cannot confirm this issue, so please provide me with more information: the _YAML configuration of the card_ and _the attributes of your mowers_.
@crazychatting This error may occur if you don't have any attributes in your mower. However, even when I use `entity: sensor` or `entity: vacuum.vacuum` instead of `entity: vacuum.mower`, I don't encounter any errors in the console.

**Comment by Barma-lej** [comment]
There is a new beta version [1.0.0b2](https://github.com/Barma-lej/landroid-card/releases/tag/1.0.0b2) here
